### ISSUE TITLE
Link on Repos list delivers 'Invalid' notice on import

### ISSUE THREAD

**Issue by Kurdaitcha** [Suzuki-Re/Suzuki-Scripts#2]
![invalid](https://github.com/Suzuki-Re/Suzuki-Scripts/assets/164469541/ba93687e-1b06-4abc-80a0-076ce757f1c6)

Links derived from https://reapack.com/repos and subsequent github page deliver the above Invalid notification when attempting to import

**Comment by Suzuki-Re** [comment]
You imported a direct github link. Try this index link
https://github.com/Suzuki-Re/Suzuki-Scripts/raw/master/index.xml
