### ISSUE TITLE
Suzuki_ReaDrum_Machine_Instruments_Rack.lua:29: attempt to call a nil value (field 'ImGui_GetBuiltinPath')

### ISSUE THREAD

**Issue by jacksorjacksor** [Suzuki-Re/Suzuki-Scripts#4]
Hi there!

Just trying a fresh install of ReaDrum. When I run either the `Suzuki_ReaDrum_Machine_Instruments_Rack.lua` or `Suzuki_ReaDrum_Machine_Instruments_Rack_(Scrollable Layout).lua` actions I get the following error:

`Suzuki_ReaDrum_Machine_Instruments_Rack.lua:29: attempt to call a nil value (field 'ImGui_GetBuiltinPath')`

Any idea what I can do to resolve this?

TIA!

Rich
- Reaper v7.15

**Comment by Suzuki-Re** [comment]
Hi, thanks for trying out my script and the report!

Probably are you using the older version of ReaImGui? ImGui_GetBuiltinPath is added in ReaImGui v0.9+ and that's one of the prerequisites. Could you check the version, and possibly install the latest ReaImGui, restart REAPER and report it back?

Maybe I can add one more check that users install the correct ReaImGui version.

**Comment by jacksorjacksor** [comment]
My pleasure!

Ah yeah, that's fixed it - I reinstalled the RealmGui v0.9.1, which then prompted a bunch of other extensions to be updated, and now ReaDrum's working fine!

Thanks for the pointer!
Rich
